# 数据库访问配置
# 主数据源，默认的
spring:
    application:
        version: 1.0
        name: 票务系统
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.1.72:8066/A0DB?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#        username: root
#        password: bymycat1674
        url: jdbc:mysql://127.0.0.1:3306/vote?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&allowMultiQueries=true
        username: root
        password: root
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测检测需要关闭的空闲连接单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        #spring.datasource.useGlobalDataSourceStat=true
        #缓存服务器
    redis:
        port: 6379
        database: 0
        host: 127.0.0.1
        password:   
#    redis:
#       port: 6379
#       database: 0
#       host: 192.168.1.163
#       password: 123456       
mybatis:
    # 指定全局配置文件位置
    config-location: classpath:mybatis-config.xml
    #配置sprintboot允许文件通过的大小
    http:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
thymeleaf:
    cache: false
    